version: '2'
services:

### Nginx Server Container #############################

  nginx:
      build: ./etc/nginx
      privileged: true
      ports:
        - "80:80"
        - "443:443"
      links:
        - "php71"
        - "php56"
      volumes:
        - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./vhost/:/etc/nginx/conf.d/
        - ../www/:/var/www/
        - ./logs/nginx/:/var/log/nginx/

### PHP Container #############################

  php71:
      build:
        context: ./etc/php71
        dockerfile: Dockerfile
        args:
          - INSTALL_XDEBUG=true
      privileged: true
      ports:
        - "9071:9000"
      links:
        - "mysql57"
        - "mysql56"
        - "redis"
      volumes:
        - ../www/:/var/www/
        - ./etc/php71/php.ini:/usr/local/etc/php/php.ini
        - ./etc/php71/php-fpm.conf:/usr/local/etc/php-fpm.conf
        - ./etc/php71/ext:/usr/local/lib/ext
        - ./logs/php/xdebug/:/tmp/

  php56:
      build: ./etc/php56
      privileged: true
      ports:
        - "9056:9000"
      links:
        - "mysql57"
        - "mysql56"
        - "mongo"
      volumes:
        - ../www/:/var/www/
        - ./etc/php56/php.ini:/usr/local/etc/php/php.ini
        - ./etc/php56/php-fpm.conf:/usr/local/etc/php-fpm.conf

### MYSQL Container #############################

  mysql57:
      build: ./etc/mysql57
      privileged: true
      ports:
        - "3306:3306"
      volumes:
        - ./data/mysql57:/var/lib/mysql
        - ./logs/mysql57/:/var/log/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=kfkdock

  mysql56:
      build: ./etc/mysql56
      privileged: true
      ports:
        - "33056:3306"
      volumes:
        - ./data/mysql56:/var/lib/mysql
        - ./logs/mysql56/:/var/log/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=kfkdock

### PostgreSQL Container ####################################

  postgres:
      build: ./etc/postgresql
      ports:
        - "5432:5432"
      volumes:
        - ./data/postgresql:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=default
        - POSTGRES_USER=default
        - POSTGRES_PASSWORD=kfkdock

### Redis Container #############################

  redis:
      build: ./etc/redis
      privileged: true
      ports:
        - "6379:6379"
      volumes:
        - ./data/redis:/data
        - ./logs/redis:/var/log/redis

### Mongo Container #############################

  mongo:
      build: ./etc/mongo
      privileged: true
      ports:
        - "27017:27017"
      volumes:
        - ./data/mongo:/data/db